main:
  push:
    - imports:
        # 引用密钥仓库中的特定文件
        - https://cnb.cool/lijc210/secret/-/blob/main/env.prod.yml
      stages:
        # - name: 读取版本号并打tag
        #   script: |
        #     VERSION=$(grep '^version' pyproject.toml | head -1 | sed 's/version = "\(.*\)"/\1/')
        #     echo "版本号: $VERSION"
        #     git tag "v$VERSION"

        - name: 同步到github
          image: tencentcom/git-sync
          env:
          settings:
            target_url: https://github.com/lijc210/sms_forwarding.git
            auth_type: https
            username: ${GITHUB_USER}
            password: ${GITHUB_TOKEN}
            sync_mode: push # 推送
            force: true # 强制推送
            push_tags: true

dev:
  push:
    - imports:
        - https://cnb.cool/lijc210/secret/-/blob/main/env.prod.yml
      stages:
        - name: 同步到github
          image: tencentcom/git-sync
          env:
          settings:
            target_url: https://github.com/lijc210/sms_forwarding.git
            auth_type: https
            username: ${GITHUB_USER}
            password: ${GITHUB_TOKEN}
            sync_mode: push
            force: true
            push_tags: true
